#!/usr/bin/env python3
"""Generate syscall/ztypes_redox_amd64.go and syscall/zerrors_redox_amd64.go.

Both come from the real `go tool cgo -godefs` run with $CC set to a wrapper
around redoxer's cross compiler, so every value/layout is taken from relibc's
actual generated headers (nothing hand-written):

  * ztypes: `cgo -godefs types_redox.go`
  * zerrors: the set of constant NAMES is taken from zerrors_linux_amd64.go
    (the broadest list Go's syscall package knows), probed through cgo against
    relibc's headers; any name relibc doesn't provide is dropped and reported.
    The error/signal *tables* are copied from the Linux file because relibc
    uses Linux's errno and signal numbering (asserted by the value checks in
    defs-crosscheck for the runtime's subset).

Run from the repo root. Output goes to src/syscall/ (in the working tree).
"""
import os
import re
import shutil
import subprocess
import sys

SYS = "src/syscall"
WORK = "/tmp/gensyscall"

INCLUDES = """\
#include <errno.h>
#include <dirent.h>
#include <fcntl.h>
#include <signal.h>
#include <termios.h>
#include <stdio.h>
#include <unistd.h>
#include <limits.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <sys/file.h>
#include <net/if.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
"""


def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def cgo_godefs(gofile, src_lines, env):
    """Run cgo -godefs, dropping lines that mention unresolved C names."""
    dropped = []
    for attempt in range(12):
        open(f"{WORK}/{gofile}", "w").write("\n".join(src_lines) + "\n")
        r = sh(["go", "tool", "cgo", "-godefs", gofile], cwd=WORK, env=env)
        if r.returncode == 0:
            return r.stdout, dropped
        names = set(re.findall(r"could not determine (?:what|kind of name for) C\.(\w+)", r.stderr))
        print(f"--- cgo {gofile} attempt {attempt + 1} failed; unresolved: {sorted(names)}")
        if not names:
            print(r.stderr[-4000:])
            sys.exit(f"cgo failed on {gofile} for a reason other than unresolved C names")
        dropped += sorted(names)
        pat = re.compile(r"\bC\.(%s)\b" % "|".join(map(re.escape, names)))
        src_lines = [l for l in src_lines if not pat.search(l)]
    sys.exit("too many cgo attempts")


def main():
    shutil.rmtree(WORK, ignore_errors=True)
    os.makedirs(WORK)
    env = dict(os.environ, GOARCH="amd64", CGO_ENABLED="1")

    # ---- ztypes ---------------------------------------------------------
    types_src = open(f"{SYS}/types_redox.go").read().split("\n")
    out, dropped = cgo_godefs("types_redox.go", types_src, env)
    if dropped:
        print("ztypes: dropped unresolved C names:", dropped)
    out = out.replace("// cgo -godefs types_redox.go", "// cgo -godefs types_redox.go (run against relibc headers via redoxer cc)")
    open(f"{SYS}/ztypes_redox_amd64.go", "w").write(out)
    print(f"wrote {SYS}/ztypes_redox_amd64.go ({len(out.splitlines())} lines)")

    # ---- zerrors --------------------------------------------------------
    linux = open(f"{SYS}/zerrors_linux_amd64.go").read()
    m_err = re.search(r"^// Errors\nconst \((.*?)^\)", linux, re.S | re.M)
    m_sig = re.search(r"^// Signals\nconst \((.*?)^\)", linux, re.S | re.M)
    assert m_err and m_sig, "cannot find Errors/Signals blocks in zerrors_linux_amd64.go"
    first_block = re.search(r"^const \((.*?)^\)", linux, re.S | re.M).group(1)

    def names(block):
        return [m.group(1) for m in re.finditer(r"^\s+(\w+)\s*=", block, re.M)]

    plain = names(first_block)
    errs = names(m_err.group(1))
    sigs = names(m_sig.group(1))
    plain_set, err_set, sig_set = set(errs), set(errs), set(sigs)
    allnames = list(dict.fromkeys(plain + errs + sigs))

    body = "\n".join(f"\t{n} = C.{n}" for n in allnames)
    probe = f"""package syscall

/*
{INCLUDES}*/
import "C"

const (
{body}
)
"""
    out, dropped = cgo_godefs("_const.go", probe.split("\n"), env)
    print("zerrors: names not provided by relibc's headers:", len(dropped))
    print(" ".join(dropped))
    vals = {}
    for m in re.finditer(r"^\s+(\w+)\s+= (.+?)\s*$", out, re.M):
        vals[m.group(1)] = m.group(2)

    def fmt_block(ns, wrap=None):
        lines = []
        for n in ns:
            if n in vals:
                v = vals[n]
                lines.append(f"\t{n} = {wrap}({v})" if wrap else f"\t{n} = {v}")
        return "\n".join(lines)

    plain_only = [n for n in plain if n not in err_set and n not in sig_set]
    tables = linux[linux.index("// Error table"):]
    z = f"""// Generated by .github/redox/gen_syscall.py from `cgo -godefs` run against
// relibc's headers via redoxer's cross compiler; the constant names come from
// zerrors_linux_amd64.go and the tables are copied from it (relibc uses
// Linux's errno and signal numbering).
// Code generated by cmd/cgo -godefs; DO NOT EDIT.

package syscall

const (
{fmt_block(plain_only)}
)

// Errors
const (
{fmt_block(errs, "Errno")}
)

// Signals
const (
{fmt_block(sigs, "Signal")}
)

{tables}"""
    open(f"{SYS}/zerrors_redox_amd64.go", "w").write(z)
    print(f"wrote {SYS}/zerrors_redox_amd64.go: {len([n for n in plain_only if n in vals])} consts, "
          f"{len([n for n in errs if n in vals])} errnos, {len([n for n in sigs if n in vals])} signals")
    missing_err = [n for n in errs if n not in vals]
    missing_sig = [n for n in sigs if n not in vals]
    print("errnos missing in relibc:", missing_err)
    print("signals missing in relibc:", missing_sig)


if __name__ == "__main__":
    main()
