// Code generated by poc/mkhurd.sh run on real GNU/Hurd amd64; DO NOT EDIT.

package syscall

const (
	AF_APPLETALK                     = 0x10
	AF_CCITT                         = 0xa
	AF_CHAOS                         = 0x5
	AF_CNT                           = 0x15
	AF_COIP                          = 0x14
	AF_DATAKIT                       = 0x9
	AF_DECnet                        = 0xc
	AF_DLI                           = 0xd
	AF_ECMA                          = 0x8
	AF_FILE                          = 0x1
	AF_HYLINK                        = 0xf
	AF_IMPLINK                       = 0x3
	AF_INET                          = 0x2
	AF_INET6                         = 0x1a
	AF_IPX                           = 0x17
	AF_ISO                           = 0x7
	AF_LAT                           = 0xe
	AF_LOCAL                         = 0x1
	AF_MAX                           = 0x1b
	AF_NS                            = 0x6
	AF_OSI                           = 0x7
	AF_PUP                           = 0x4
	AF_SIP                           = 0x18
	AF_SNA                           = 0xb
	AF_UNIX                          = 0x1
	AF_UNSPEC                        = 0x0
	AT_EACCESS                       = 0x200
	AT_EMPTY_PATH                    = 0x1000
	AT_FDCWD                         = -0x64
	AT_NO_AUTOMOUNT                  = 0x800
	AT_RECURSIVE                     = 0x8000
	AT_REMOVEDIR                     = 0x200
	AT_STATX_DONT_SYNC               = 0x4000
	AT_STATX_FORCE_SYNC              = 0x2000
	AT_STATX_SYNC_AS_STAT            = 0x0
	AT_STATX_SYNC_TYPE               = 0x6000
	AT_SYMLINK_FOLLOW                = 0x400
	AT_SYMLINK_NOFOLLOW              = 0x100
	B0                               = 0x0
	B1000000                         = 0xf4240
	B10000000                        = 0x989680
	B110                             = 0x6e
	B115200                          = 0x1c200
	B1152000                         = 0x119400
	B1200                            = 0x4b0
	B134                             = 0x86
	B14400                           = 0x3840
	B150                             = 0x96
	B1500000                         = 0x16e360
	B153600                          = 0x25800
	B1800                            = 0x708
	B19200                           = 0x4b00
	B200                             = 0xc8
	B2000000                         = 0x1e8480
	B230400                          = 0x38400
	B2400                            = 0x960
	B2500000                         = 0x2625a0
	B28800                           = 0x7080
	B300                             = 0x12c
	B3000000                         = 0x2dc6c0
	B307200                          = 0x4b000
	B33600                           = 0x8340
	B3500000                         = 0x3567e0
	B38400                           = 0x9600
	B4000000                         = 0x3d0900
	B460800                          = 0x70800
	B4800                            = 0x12c0
	B50                              = 0x32
	B500000                          = 0x7a120
	B5000000                         = 0x4c4b40
	B57600                           = 0xe100
	B576000                          = 0x8ca00
	B600                             = 0x258
	B614400                          = 0x96000
	B7200                            = 0x1c20
	B75                              = 0x4b
	B76800                           = 0x12c00
	B921600                          = 0xe1000
	B9600                            = 0x2580
	BRKINT                           = 0x2
	CFLUSH                           = 0xf
	CLOCAL                           = 0x8000
	CREAD                            = 0x800
	CS5                              = 0x0
	CS6                              = 0x100
	CS7                              = 0x200
	CS8                              = 0x300
	CSIZE                            = 0x300
	CSTART                           = 0x11
	CSTATUS                          = 0x14
	CSTOP                            = 0x13
	CSTOPB                           = 0x400
	CSUSP                            = 0x1a
	DT_BLK                           = 0x6
	DT_CHR                           = 0x2
	DT_DIR                           = 0x4
	DT_FIFO                          = 0x1
	DT_LNK                           = 0xa
	DT_REG                           = 0x8
	DT_SOCK                          = 0xc
	DT_UNKNOWN                       = 0x0
	DT_WHT                           = 0xe
	ECHO                             = 0x8
	ECHOCTL                          = 0x40
	ECHOE                            = 0x2
	ECHOK                            = 0x4
	ECHOKE                           = 0x1
	ECHONL                           = 0x10
	ECHOPRT                          = 0x20
	ED_ALREADY_OPEN                  = 0x9c7
	ED_DEVICE_DOWN                   = 0x9c8
	ED_INVALID_OPERATION             = 0x9c9
	ED_INVALID_RECNUM                = 0x9ca
	ED_INVALID_SIZE                  = 0x9cb
	ED_IO_ERROR                      = 0x9c4
	ED_NO_MEMORY                     = 0x9cc
	ED_NO_SUCH_DEVICE                = 0x9c6
	ED_READ_ONLY                     = 0x9cd
	ED_WOULD_BLOCK                   = 0x9c5
	EKERN_ABORTED                    = 0xe
	EKERN_FAILURE                    = 0x5
	EKERN_INTERRUPTED                = 0x1c
	EKERN_INVALID_ADDRESS            = 0x1
	EKERN_INVALID_ARGUMENT           = 0x4
	EKERN_INVALID_CAPABILITY         = 0x14
	EKERN_INVALID_HOST               = 0x16
	EKERN_INVALID_NAME               = 0xf
	EKERN_INVALID_RIGHT              = 0x11
	EKERN_INVALID_TASK               = 0x10
	EKERN_INVALID_VALUE              = 0x12
	EKERN_MEMORY_ERROR               = 0xa
	EKERN_MEMORY_FAILURE             = 0x9
	EKERN_MEMORY_PRESENT             = 0x17
	EKERN_NAME_EXISTS                = 0xd
	EKERN_NOT_IN_SET                 = 0xc
	EKERN_NOT_RECEIVER               = 0x7
	EKERN_NO_ACCESS                  = 0x8
	EKERN_NO_SPACE                   = 0x3
	EKERN_PROTECTION_FAILURE         = 0x2
	EKERN_RESOURCE_SHORTAGE          = 0x6
	EKERN_RIGHT_EXISTS               = 0x15
	EKERN_TERMINATED                 = 0x1a
	EKERN_TIMEDOUT                   = 0x1b
	EKERN_UREFS_OVERFLOW             = 0x13
	EKERN_WRITE_PROTECTION_FAILURE   = 0x18
	EMACH_RCV_BODY_ERROR             = 0x1000400c
	EMACH_RCV_HEADER_ERROR           = 0x1000400b
	EMACH_RCV_INTERRUPTED            = 0x10004005
	EMACH_RCV_INVALID_DATA           = 0x10004008
	EMACH_RCV_INVALID_NAME           = 0x10004002
	EMACH_RCV_INVALID_NOTIFY         = 0x10004007
	EMACH_RCV_IN_PROGRESS            = 0x10004001
	EMACH_RCV_IN_SET                 = 0x1000400a
	EMACH_RCV_PORT_CHANGED           = 0x10004006
	EMACH_RCV_PORT_DIED              = 0x10004009
	EMACH_RCV_TIMED_OUT              = 0x10004003
	EMACH_RCV_TOO_LARGE              = 0x10004004
	EMACH_SEND_INTERRUPTED           = 0x10000007
	EMACH_SEND_INVALID_DATA          = 0x10000002
	EMACH_SEND_INVALID_DEST          = 0x10000003
	EMACH_SEND_INVALID_HEADER        = 0x10000010
	EMACH_SEND_INVALID_MEMORY        = 0x1000000c
	EMACH_SEND_INVALID_NOTIFY        = 0x1000000b
	EMACH_SEND_INVALID_REPLY         = 0x10000009
	EMACH_SEND_INVALID_RIGHT         = 0x1000000a
	EMACH_SEND_INVALID_TYPE          = 0x1000000f
	EMACH_SEND_IN_PROGRESS           = 0x10000001
	EMACH_SEND_MSG_TOO_SMALL         = 0x10000008
	EMACH_SEND_NOTIFY_IN_PROGRESS    = 0x10000006
	EMACH_SEND_NO_BUFFER             = 0x1000000d
	EMACH_SEND_NO_NOTIFY             = 0x1000000e
	EMACH_SEND_TIMED_OUT             = 0x10000004
	EMACH_SEND_WILL_NOTIFY           = 0x10000005
	EMIG_ARRAY_TOO_LARGE             = -0x133
	EMIG_BAD_ARGUMENTS               = -0x130
	EMIG_BAD_ID                      = -0x12f
	EMIG_DESTROY_REQUEST             = -0x135
	EMIG_EXCEPTION                   = -0x132
	EMIG_NO_REPLY                    = -0x131
	EMIG_REMOTE_ERROR                = -0x12e
	EMIG_REPLY_MISMATCH              = -0x12d
	EMIG_SERVER_DIED                 = -0x134
	EMIG_TYPE_ERROR                  = -0x12c
	EVENP                            = 0x80
	EXEC_PAGESIZE                    = 0x1000
	EXTA                             = 0x4b00
	EXTB                             = 0x9600
	EXTPROC                          = 0x800
	FD_CLOEXEC                       = 0x1
	FD_SETSIZE                       = 0x100
	FLUSHO                           = 0x800000
	F_DUPFD                          = 0x0
	F_DUPFD_CLOEXEC                  = 0x406
	F_GETFD                          = 0x1
	F_GETFL                          = 0x3
	F_GETLK                          = 0x7
	F_GETLK64                        = 0xa
	F_GETOWN                         = 0x5
	F_LOCK                           = 0x1
	F_OK                             = 0x0
	F_RDLCK                          = 0x1
	F_SETFD                          = 0x2
	F_SETFL                          = 0x4
	F_SETLK                          = 0x8
	F_SETLK64                        = 0xb
	F_SETLKW                         = 0x9
	F_SETLKW64                       = 0xc
	F_SETOWN                         = 0x6
	F_TEST                           = 0x3
	F_TLOCK                          = 0x2
	F_ULOCK                          = 0x0
	F_UNLCK                          = 0x3
	F_WRLCK                          = 0x2
	HUPCL                            = 0x4000
	ICANON                           = 0x100
	ICMP6_DST_UNREACH                = 0x1
	ICMP6_DST_UNREACH_ADDR           = 0x3
	ICMP6_DST_UNREACH_ADMIN          = 0x1
	ICMP6_DST_UNREACH_BEYONDSCOPE    = 0x2
	ICMP6_DST_UNREACH_NOPORT         = 0x4
	ICMP6_DST_UNREACH_NOROUTE        = 0x0
	ICMP6_ECHO_REPLY                 = 0x81
	ICMP6_ECHO_REQUEST               = 0x80
	ICMP6_FILTER                     = 0x1
	ICMP6_FILTER_BLOCK               = 0x1
	ICMP6_FILTER_BLOCKOTHERS         = 0x3
	ICMP6_FILTER_PASS                = 0x2
	ICMP6_FILTER_PASSONLY            = 0x4
	ICMP6_INFOMSG_MASK               = 0x80
	ICMP6_PACKET_TOO_BIG             = 0x2
	ICMP6_PARAMPROB_HEADER           = 0x0
	ICMP6_PARAMPROB_NEXTHEADER       = 0x1
	ICMP6_PARAMPROB_OPTION           = 0x2
	ICMP6_PARAM_PROB                 = 0x4
	ICMP6_ROUTER_RENUMBERING         = 0x8a
	ICMP6_RR_FLAGS_FORCEAPPLY        = 0x20
	ICMP6_RR_FLAGS_PREVDONE          = 0x8
	ICMP6_RR_FLAGS_REQRESULT         = 0x40
	ICMP6_RR_FLAGS_SPECSITE          = 0x10
	ICMP6_RR_FLAGS_TEST              = 0x80
	ICMP6_RR_PCOUSE_FLAGS_DECRPLTIME = 0x40
	ICMP6_RR_PCOUSE_FLAGS_DECRVLTIME = 0x80
	ICMP6_RR_PCOUSE_RAFLAGS_AUTO     = 0x10
	ICMP6_RR_PCOUSE_RAFLAGS_ONLINK   = 0x20
	ICMP6_RR_RESULT_FLAGS_FORBIDDEN  = 0x100
	ICMP6_RR_RESULT_FLAGS_OOB        = 0x200
	ICMP6_TIME_EXCEEDED              = 0x3
	ICMP6_TIME_EXCEED_REASSEMBLY     = 0x1
	ICMP6_TIME_EXCEED_TRANSIT        = 0x0
	ICRNL                            = 0x100
	IEXTEN                           = 0x400
	IFF_ALLMULTI                     = 0x200
	IFF_AUTOMEDIA                    = 0x4000
	IFF_BROADCAST                    = 0x2
	IFF_DEBUG                        = 0x4
	IFF_DYNAMIC                      = 0x8000
	IFF_LOOPBACK                     = 0x8
	IFF_MASTER                       = 0x400
	IFF_MULTICAST                    = 0x1000
	IFF_NOARP                        = 0x80
	IFF_NOTRAILERS                   = 0x20
	IFF_POINTOPOINT                  = 0x10
	IFF_PORTSEL                      = 0x2000
	IFF_PROMISC                      = 0x100
	IFF_RUNNING                      = 0x40
	IFF_SLAVE                        = 0x800
	IFF_UP                           = 0x1
	IFNAMSIZ                         = 0x10
	IGNBRK                           = 0x1
	IGNCR                            = 0x80
	IGNPAR                           = 0x4
	IMAXBEL                          = 0x2000
	INLCR                            = 0x40
	INPCK                            = 0x10
	IN_CLASSA_HOST                   = 0xffffff
	IN_CLASSA_MAX                    = 0x80
	IN_CLASSA_NET                    = 0xff000000
	IN_CLASSA_NSHIFT                 = 0x18
	IN_CLASSB_HOST                   = 0xffff
	IN_CLASSB_MAX                    = 0x10000
	IN_CLASSB_NET                    = 0xffff0000
	IN_CLASSB_NSHIFT                 = 0x10
	IN_CLASSC_HOST                   = 0xff
	IN_CLASSC_NET                    = 0xffffff00
	IN_CLASSC_NSHIFT                 = 0x8
	IN_LOOPBACKNET                   = 0x7f
	IPPROTO_AH                       = 0x33
	IPPROTO_BEETPH                   = 0x5e
	IPPROTO_COMP                     = 0x6c
	IPPROTO_DCCP                     = 0x21
	IPPROTO_DSTOPTS                  = 0x3c
	IPPROTO_EGP                      = 0x8
	IPPROTO_ENCAP                    = 0x62
	IPPROTO_ESP                      = 0x32
	IPPROTO_ETHERNET                 = 0x8f
	IPPROTO_FRAGMENT                 = 0x2c
	IPPROTO_GRE                      = 0x2f
	IPPROTO_HOPOPTS                  = 0x0
	IPPROTO_ICMP                     = 0x1
	IPPROTO_ICMPV6                   = 0x3a
	IPPROTO_IDP                      = 0x16
	IPPROTO_IGMP                     = 0x2
	IPPROTO_IP                       = 0x0
	IPPROTO_IPIP                     = 0x4
	IPPROTO_IPV6                     = 0x29
	IPPROTO_L2TP                     = 0x73
	IPPROTO_MH                       = 0x87
	IPPROTO_MPLS                     = 0x89
	IPPROTO_MPTCP                    = 0x106
	IPPROTO_MTP                      = 0x5c
	IPPROTO_NONE                     = 0x3b
	IPPROTO_PIM                      = 0x67
	IPPROTO_PUP                      = 0xc
	IPPROTO_RAW                      = 0xff
	IPPROTO_ROUTING                  = 0x2b
	IPPROTO_RSVP                     = 0x2e
	IPPROTO_SCTP                     = 0x84
	IPPROTO_SMC                      = 0x100
	IPPROTO_TCP                      = 0x6
	IPPROTO_TP                       = 0x1d
	IPPROTO_UDP                      = 0x11
	IPPROTO_UDPLITE                  = 0x88
	IPV6_2292DSTOPTS                 = 0x4
	IPV6_2292HOPLIMIT                = 0x8
	IPV6_2292HOPOPTS                 = 0x3
	IPV6_2292PKTINFO                 = 0x2
	IPV6_2292PKTOPTIONS              = 0x6
	IPV6_2292RTHDR                   = 0x5
	IPV6_ADDRFORM                    = 0x1
	IPV6_ADDR_PREFERENCES            = 0x48
	IPV6_ADD_MEMBERSHIP              = 0x14
	IPV6_CHECKSUM                    = 0x7
	IPV6_DONTFRAG                    = 0x3e
	IPV6_DROP_MEMBERSHIP             = 0x15
	IPV6_DSTOPTS                     = 0x3b
	IPV6_HOPLIMIT                    = 0x34
	IPV6_HOPOPTS                     = 0x36
	IPV6_JOIN_ANYCAST                = 0x1b
	IPV6_JOIN_GROUP                  = 0x14
	IPV6_LEAVE_ANYCAST               = 0x1c
	IPV6_LEAVE_GROUP                 = 0x15
	IPV6_MINHOPCOUNT                 = 0x49
	IPV6_MTU                         = 0x18
	IPV6_MTU_DISCOVER                = 0x17
	IPV6_MULTICAST_HOPS              = 0x12
	IPV6_MULTICAST_IF                = 0x11
	IPV6_MULTICAST_LOOP              = 0x13
	IPV6_PATHMTU                     = 0x3d
	IPV6_PKTINFO                     = 0x32
	IPV6_PMTUDISC_DO                 = 0x2
	IPV6_PMTUDISC_DONT               = 0x0
	IPV6_PMTUDISC_INTERFACE          = 0x4
	IPV6_PMTUDISC_OMIT               = 0x5
	IPV6_PMTUDISC_PROBE              = 0x3
	IPV6_PMTUDISC_WANT               = 0x1
	IPV6_RECVDSTOPTS                 = 0x3a
	IPV6_RECVERR                     = 0x19
	IPV6_RECVHOPLIMIT                = 0x33
	IPV6_RECVHOPOPTS                 = 0x35
	IPV6_RECVPATHMTU                 = 0x3c
	IPV6_RECVPKTINFO                 = 0x31
	IPV6_RECVRTHDR                   = 0x38
	IPV6_RECVTCLASS                  = 0x42
	IPV6_ROUTER_ALERT                = 0x16
	IPV6_RTHDR                       = 0x39
	IPV6_RTHDRDSTOPTS                = 0x37
	IPV6_RTHDR_LOOSE                 = 0x0
	IPV6_RTHDR_STRICT                = 0x1
	IPV6_RTHDR_TYPE_0                = 0x0
	IPV6_RXDSTOPTS                   = 0x4
	IPV6_RXHOPOPTS                   = 0x3
	IPV6_RXINFO                      = 0x2
	IPV6_TCLASS                      = 0x43
	IPV6_TXINFO                      = 0x2
	IPV6_UNICAST_HOPS                = 0x10
	IPV6_V6ONLY                      = 0x1a
	IP_ADD_MEMBERSHIP                = 0xc
	IP_DROP_MEMBERSHIP               = 0xd
	IP_HDRINCL                       = 0x2
	IP_MULTICAST_IF                  = 0x9
	IP_MULTICAST_LOOP                = 0xb
	IP_MULTICAST_TTL                 = 0xa
	IP_OPTIONS                       = 0x1
	IP_PMTUDISC_DO                   = 0x2
	IP_PMTUDISC_DONT                 = 0x0
	IP_PMTUDISC_INTERFACE            = 0x4
	IP_PMTUDISC_OMIT                 = 0x5
	IP_PMTUDISC_PROBE                = 0x3
	IP_PMTUDISC_WANT                 = 0x1
	IP_RECVDSTADDR                   = 0x7
	IP_RECVOPTS                      = 0x5
	IP_RECVRETOPTS                   = 0x6
	IP_RETOPTS                       = 0x8
	IP_TOS                           = 0x3
	IP_TTL                           = 0x4
	ISIG                             = 0x80
	ISTRIP                           = 0x20
	IXANY                            = 0x800
	IXOFF                            = 0x400
	IXON                             = 0x200
	LOCK_EX                          = 0x2
	LOCK_NB                          = 0x4
	LOCK_SH                          = 0x1
	LOCK_UN                          = 0x8
	MADV_DONTNEED                    = 0x4
	MADV_NORMAL                      = 0x0
	MADV_RANDOM                      = 0x1
	MADV_SEQUENTIAL                  = 0x2
	MADV_WILLNEED                    = 0x3
	MAP_32BIT                        = 0x1000
	MAP_ANON                         = 0x2
	MAP_ANONYMOUS                    = 0x2
	MAP_COPY                         = 0x20
	MAP_EXCL                         = 0x4000
	MAP_FILE                         = 0x1
	MAP_FIXED                        = 0x100
	MAP_FIXED_NOREPLACE              = 0x4100
	MAP_HASSEMAPHORE                 = 0x400
	MAP_INHERIT                      = 0x800
	MAP_NOEXTEND                     = 0x200
	MAP_NORESERVE                    = 0x2000
	MAP_PRIVATE                      = 0x0
	MAP_SHARED                       = 0x10
	MAP_TRYFIXED                     = 0x4100
	MAP_TYPE                         = 0xf
	MCL_CURRENT                      = 0x1
	MCL_FUTURE                       = 0x2
	MSG_CMSG_CLOEXEC                 = 0x40000
	MSG_CTRUNC                       = 0x20
	MSG_DONTROUTE                    = 0x4
	MSG_DONTWAIT                     = 0x80
	MSG_EOR                          = 0x8
	MSG_NOSIGNAL                     = 0x400
	MSG_OOB                          = 0x1
	MSG_PEEK                         = 0x2
	MSG_TRUNC                        = 0x10
	MSG_WAITALL                      = 0x40
	MS_ASYNC                         = 0x1
	MS_INVALIDATE                    = 0x2
	MS_SYNC                          = 0x0
	NAME_MAX                         = 0xff
	NOFLSH                           = 0x80000000
	OCRNL                            = 0x10
	OFDEL                            = 0x80000
	OFILL                            = 0x40000
	ONLCR                            = 0x2
	ONLRET                           = 0x40
	ONOCR                            = 0x20
	ONOEOT                           = 0x8
	OPOST                            = 0x1
	O_ACCMODE                        = 0x3
	O_APPEND                         = 0x100
	O_ASYNC                          = 0x200
	O_CLOEXEC                        = 0x400000
	O_CREAT                          = 0x10
	O_DIRECTORY                      = 0x200000
	O_DSYNC                          = 0x400
	O_EXCL                           = 0x20
	O_EXEC                           = 0x4
	O_EXLOCK                         = 0x40000
	O_FSYNC                          = 0x400
	O_HURD                           = 0x6ffff
	O_IGNORE_CTTY                    = 0x80000
	O_LARGEFILE                      = 0x0
	O_NDELAY                         = 0x8
	O_NOATIME                        = 0x800
	O_NOCTTY                         = 0x0
	O_NOFOLLOW                       = 0x100000
	O_NOLINK                         = 0x40
	O_NONBLOCK                       = 0x8
	O_NORW                           = 0x0
	O_NOTRANS                        = 0x80
	O_RDONLY                         = 0x1
	O_RDWR                           = 0x3
	O_READ                           = 0x1
	O_RSYNC                          = 0x400
	O_SHLOCK                         = 0x20000
	O_SYNC                           = 0x400
	O_TMPFILE                        = 0x800000
	O_TRUNC                          = 0x10000
	O_WRITE                          = 0x2
	O_WRONLY                         = 0x2
	PARENB                           = 0x1000
	PARMRK                           = 0x8
	PARODD                           = 0x2000
	PENDIN                           = 0x20000000
	POLLERR                          = 0x8
	POLLHUP                          = 0x10
	POLLIN                           = 0x1
	POLLNVAL                         = 0x20
	POLLOUT                          = 0x4
	POLLPRI                          = 0x2
	POLLRDBAND                       = 0x2
	POLLRDNORM                       = 0x1
	POLLWRBAND                       = 0x4
	POLLWRNORM                       = 0x4
	PRIO_PGRP                        = 0x1
	PRIO_PROCESS                     = 0x0
	PRIO_USER                        = 0x2
	PROT_EXEC                        = 0x1
	PROT_NONE                        = 0x0
	PROT_READ                        = 0x4
	PROT_WRITE                       = 0x2
	RLIMIT_AS                        = 0xa
	RLIMIT_CORE                      = 0x4
	RLIMIT_CPU                       = 0x0
	RLIMIT_DATA                      = 0x2
	RLIMIT_FSIZE                     = 0x1
	RLIMIT_NOFILE                    = 0x8
	RLIMIT_STACK                     = 0x3
	RLIM_INFINITY                    = 0x7fffffff
	RUSAGE_CHILDREN                  = -0x1
	RUSAGE_SELF                      = 0x0
	SCM_CREDS                        = 0x3
	SCM_RIGHTS                       = 0x1
	SCM_SRCINFO                      = 0x2
	SCM_TIMESTAMP                    = 0x2
	SHUT_RD                          = 0x0
	SHUT_RDWR                        = 0x2
	SHUT_WR                          = 0x1
	SIOCATMARK                       = 0x60080687
	SIOCDIFADDR                      = 0x80840199
	SIOCGIFADDR                      = 0xc08401a1
	SIOCGIFBRDADDR                   = 0xc08401a3
	SIOCGIFCONF                      = 0xc00801a4
	SIOCGIFDSTADDR                   = 0xc08401a2
	SIOCGIFFLAGS                     = 0xc4804191
	SIOCGIFHWADDR                    = 0xc08401a7
	SIOCGIFINDEX                     = 0xc88041da
	SIOCGIFMETRIC                    = 0xc8804197
	SIOCGIFMTU                       = 0xc88041b3
	SIOCGIFNAME                      = 0xc88041db
	SIOCGIFNETMASK                   = 0xc08401a5
	SIOCGPGRP                        = 0x60080689
	SIOCSIFADDR                      = 0x8084018c
	SIOCSIFBRDADDR                   = 0x80840193
	SIOCSIFDSTADDR                   = 0x8084018e
	SIOCSIFFLAGS                     = 0x84804190
	SIOCSIFMETRIC                    = 0x88804198
	SIOCSIFMTU                       = 0x888041b4
	SIOCSIFNETMASK                   = 0x80840196
	SIOCSPGRP                        = 0xa0080688
	SOCK_CLOEXEC                     = 0x400000
	SOCK_DGRAM                       = 0x2
	SOCK_MAX                         = 0x6
	SOCK_NONBLOCK                    = 0x800
	SOCK_RAW                         = 0x3
	SOCK_RDM                         = 0x4
	SOCK_SEQPACKET                   = 0x5
	SOCK_STREAM                      = 0x1
	SOCK_TYPE_MASK                   = 0xf
	SOL_ICMPV6                       = 0x3a
	SOL_IP                           = 0x0
	SOL_IPV6                         = 0x29
	SOL_SOCKET                       = 0xffff
	SOL_TCP                          = 0x6
	SOMAXCONN                        = 0x1000
	SO_ACCEPTCONN                    = 0x2
	SO_BROADCAST                     = 0x20
	SO_DEBUG                         = 0x1
	SO_DONTROUTE                     = 0x10
	SO_ERROR                         = 0x1007
	SO_KEEPALIVE                     = 0x8
	SO_LINGER                        = 0x80
	SO_OOBINLINE                     = 0x100
	SO_RCVBUF                        = 0x1002
	SO_RCVLOWAT                      = 0x1004
	SO_RCVTIMEO                      = 0x1006
	SO_REUSEADDR                     = 0x4
	SO_REUSEPORT                     = 0x200
	SO_SNDBUF                        = 0x1001
	SO_SNDLOWAT                      = 0x1003
	SO_SNDTIMEO                      = 0x1005
	SO_STYLE                         = 0x1008
	SO_TYPE                          = 0x1008
	SO_USELOOPBACK                   = 0x40
	S_BLKSIZE                        = 0x200
	S_IATRANS                        = 0x400000
	S_IEXEC                          = 0x40
	S_IFBLK                          = 0x6000
	S_IFCHR                          = 0x2000
	S_IFDIR                          = 0x4000
	S_IFIFO                          = 0x1000
	S_IFLNK                          = 0xa000
	S_IFMT                           = 0xf000
	S_IFREG                          = 0x8000
	S_IFSOCK                         = 0xc000
	S_IMMAP0                         = 0x1000000
	S_INOCACHE                       = 0x10000
	S_IPTRANS                        = 0x200000
	S_IREAD                          = 0x100
	S_IRGRP                          = 0x20
	S_IROOT                          = 0x800000
	S_IROTH                          = 0x4
	S_IRUSR                          = 0x100
	S_IRWXG                          = 0x38
	S_IRWXO                          = 0x7
	S_IRWXU                          = 0x1c0
	S_ISGID                          = 0x400
	S_ISPARE                         = -0x2000000
	S_ISUID                          = 0x800
	S_ISVTX                          = 0x200
	S_ITRANS                         = 0xe00000
	S_IUNKNOWN                       = 0x1c0000
	S_IUNKSHIFT                      = 0xc
	S_IUSEUNK                        = 0x20000
	S_IWGRP                          = 0x10
	S_IWOTH                          = 0x2
	S_IWRITE                         = 0x80
	S_IWUSR                          = 0x80
	S_IXGRP                          = 0x8
	S_IXOTH                          = 0x1
	S_IXUSR                          = 0x40
	TCIFLUSH                         = 0x1
	TCIOFLUSH                        = 0x3
	TCOFLUSH                         = 0x2
	TCP_CC_INFO                      = 0x1a
	TCP_CM_INQ                       = 0x24
	TCP_CONGESTION                   = 0xd
	TCP_COOKIE_IN_ALWAYS             = 0x1
	TCP_COOKIE_MAX                   = 0x10
	TCP_COOKIE_MIN                   = 0x8
	TCP_COOKIE_OUT_NEVER             = 0x2
	TCP_COOKIE_PAIR_SIZE             = 0x20
	TCP_COOKIE_TRANSACTIONS          = 0xf
	TCP_CORK                         = 0x3
	TCP_DEFER_ACCEPT                 = 0x9
	TCP_FASTOPEN                     = 0x17
	TCP_FASTOPEN_CONNECT             = 0x1e
	TCP_FASTOPEN_KEY                 = 0x21
	TCP_FASTOPEN_NO_COOKIE           = 0x22
	TCP_INFO                         = 0xb
	TCP_INQ                          = 0x24
	TCP_KEEPCNT                      = 0x6
	TCP_KEEPIDLE                     = 0x4
	TCP_KEEPINTVL                    = 0x5
	TCP_LINGER2                      = 0x8
	TCP_MAXSEG                       = 0x2
	TCP_MAXWIN                       = 0xffff
	TCP_MAX_WINSHIFT                 = 0xe
	TCP_MD5SIG                       = 0xe
	TCP_MD5SIG_EXT                   = 0x20
	TCP_MD5SIG_FLAG_IFINDEX          = 0x2
	TCP_MD5SIG_FLAG_PREFIX           = 0x1
	TCP_MD5SIG_MAXKEYLEN             = 0x50
	TCP_MSS                          = 0x200
	TCP_MSS_DEFAULT                  = 0x218
	TCP_MSS_DESIRED                  = 0x4c4
	TCP_NODELAY                      = 0x1
	TCP_NOTSENT_LOWAT                = 0x19
	TCP_QUEUE_SEQ                    = 0x15
	TCP_QUICKACK                     = 0xc
	TCP_REPAIR                       = 0x13
	TCP_REPAIR_OFF                   = 0x0
	TCP_REPAIR_OFF_NO_WP             = -0x1
	TCP_REPAIR_ON                    = 0x1
	TCP_REPAIR_OPTIONS               = 0x16
	TCP_REPAIR_QUEUE                 = 0x14
	TCP_REPAIR_WINDOW                = 0x1d
	TCP_SAVED_SYN                    = 0x1c
	TCP_SAVE_SYN                     = 0x1b
	TCP_SYNCNT                       = 0x7
	TCP_S_DATA_IN                    = 0x4
	TCP_S_DATA_OUT                   = 0x8
	TCP_THIN_DUPACK                  = 0x11
	TCP_THIN_LINEAR_TIMEOUTS         = 0x10
	TCP_TIMESTAMP                    = 0x18
	TCP_TX_DELAY                     = 0x25
	TCP_ULP                          = 0x1f
	TCP_USER_TIMEOUT                 = 0x12
	TCP_WINDOW_CLAMP                 = 0xa
	TCP_ZEROCOPY_RECEIVE             = 0x23
	TCSAFLUSH                        = 0x2
	TIOCCBRK                         = 0x77a
	TIOCCDTR                         = 0x778
	TIOCCONS                         = 0xa0080762
	TIOCDRAIN                        = 0x75e
	TIOCEXCL                         = 0x70d
	TIOCEXT                          = 0xa0080760
	TIOCFLUSH                        = 0xa0080710
	TIOCGETA                         = 0x62251713
	TIOCGETC                         = 0x40300712
	TIOCGETD                         = 0x6008071a
	TIOCGETP                         = 0x44204708
	TIOCGPGRP                        = 0x60080777
	TIOCGWINSZ                       = 0x50200768
	TIOCMBIC                         = 0xa008076b
	TIOCMBIS                         = 0xa008076c
	TIOCMGET                         = 0x6008076a
	TIOCMODG                         = 0x60080703
	TIOCMODS                         = 0xa0080704
	TIOCMSET                         = 0xa008076d
	TIOCM_CAR                        = 0x40
	TIOCM_CD                         = 0x40
	TIOCM_CTS                        = 0x20
	TIOCM_DSR                        = 0x100
	TIOCM_DTR                        = 0x2
	TIOCM_LE                         = 0x1
	TIOCM_RI                         = 0x80
	TIOCM_RNG                        = 0x80
	TIOCM_RTS                        = 0x4
	TIOCM_SR                         = 0x10
	TIOCM_ST                         = 0x8
	TIOCNOTTY                        = 0x771
	TIOCNXCL                         = 0x70e
	TIOCOUTQ                         = 0x60080773
	TIOCPKT                          = 0xa0080770
	TIOCPKT_DATA                     = 0x0
	TIOCPKT_DOSTOP                   = 0x20
	TIOCPKT_FLUSHREAD                = 0x1
	TIOCPKT_FLUSHWRITE               = 0x2
	TIOCPKT_IOCTL                    = 0x40
	TIOCPKT_NOSTOP                   = 0x10
	TIOCPKT_START                    = 0x8
	TIOCPKT_STOP                     = 0x4
	TIOCREMOTE                       = 0xa0080769
	TIOCSBRK                         = 0x77b
	TIOCSCTTY                        = 0x761
	TIOCSDTR                         = 0x779
	TIOCSETA                         = 0xa2251714
	TIOCSETAF                        = 0xa2251716
	TIOCSETAW                        = 0xa2251715
	TIOCSETC                         = 0x80300711
	TIOCSETD                         = 0xa008071b
	TIOCSETN                         = 0x8420470a
	TIOCSETP                         = 0x84204709
	TIOCSIG                          = 0x75f
	TIOCSPGRP                        = 0xa0080776
	TIOCSTART                        = 0x76e
	TIOCSTI                          = 0x80080772
	TIOCSTOP                         = 0x76f
	TIOCSWINSZ                       = 0x90200767
	TIOCUCNTL                        = 0xa0080766
	TOSTOP                           = 0x400000
	UTIME_NOW                        = -0x1
	UTIME_OMIT                       = -0x2
	VDISCARD                         = 0xf
	VDSUSP                           = 0xb
	VEOF                             = 0x0
	VEOL                             = 0x1
	VEOL2                            = 0x2
	VERASE                           = 0x3
	VINTR                            = 0x8
	VKILL                            = 0x5
	VLNEXT                           = 0xe
	VMIN                             = 0x10
	VQUIT                            = 0x9
	VREPRINT                         = 0x6
	VSTART                           = 0xc
	VSTATUS                          = 0x12
	VSTOP                            = 0xd
	VSUSP                            = 0xa
	VT0                              = 0x0
	VT1                              = 0x10000
	VTDELAY                          = 0x4000
	VTDLY                            = 0x10000
	VTIME                            = 0x11
	VWERASE                          = 0x4
	WCONTINUED                       = 0x4
	WCOREFLAG                        = 0x80
	WEXITED                          = 0x10
	WNOHANG                          = 0x1
	WNOWAIT                          = 0x8
	WSTOPPED                         = 0x2
	WUNTRACED                        = 0x2
	_NOFLSH                          = 0x80000000
)

// Errors (Mach error codes: 0x40000000 | n)
const (
	E2BIG           = Errno(0x40000007)
	EACCES          = Errno(0x4000000d)
	EADDRINUSE      = Errno(0x40000030)
	EADDRNOTAVAIL   = Errno(0x40000031)
	EAFNOSUPPORT    = Errno(0x4000002f)
	EAGAIN          = Errno(0x40000023)
	EALREADY        = Errno(0x40000025)
	EAUTH           = Errno(0x40000050)
	EBACKGROUND     = Errno(0x40000064)
	EBADF           = Errno(0x40000009)
	EBADMSG         = Errno(0x4000006b)
	EBADRPC         = Errno(0x40000048)
	EBUSY           = Errno(0x40000010)
	ECANCELED       = Errno(0x40000077)
	ECHILD          = Errno(0x4000000a)
	ECONNABORTED    = Errno(0x40000035)
	ECONNREFUSED    = Errno(0x4000003d)
	ECONNRESET      = Errno(0x40000036)
	EDEADLK         = Errno(0x4000000b)
	EDESTADDRREQ    = Errno(0x40000027)
	EDIED           = Errno(0x40000065)
	EDOM            = Errno(0x40000021)
	EDQUOT          = Errno(0x40000045)
	EEXIST          = Errno(0x40000011)
	EFAULT          = Errno(0x4000000e)
	EFBIG           = Errno(0x4000001b)
	EFTYPE          = Errno(0x4000004f)
	EGRATUITOUS     = Errno(0x40000069)
	EGREGIOUS       = Errno(0x40000067)
	EHOSTDOWN       = Errno(0x40000040)
	EHOSTUNREACH    = Errno(0x40000041)
	EIDRM           = Errno(0x4000006c)
	EIEIO           = Errno(0x40000068)
	EILSEQ          = Errno(0x4000006a)
	EINPROGRESS     = Errno(0x40000024)
	EINTR           = Errno(0x40000004)
	EINVAL          = Errno(0x40000016)
	EIO             = Errno(0x40000005)
	EISCONN         = Errno(0x40000038)
	EISDIR          = Errno(0x40000015)
	ELIBEXEC        = Errno(0x40000053)
	ELOOP           = Errno(0x4000003e)
	EMFILE          = Errno(0x40000018)
	EMLINK          = Errno(0x4000001f)
	EMSGSIZE        = Errno(0x40000028)
	EMULTIHOP       = Errno(0x4000006d)
	ENAMETOOLONG    = Errno(0x4000003f)
	ENEEDAUTH       = Errno(0x40000051)
	ENETDOWN        = Errno(0x40000032)
	ENETRESET       = Errno(0x40000034)
	ENETUNREACH     = Errno(0x40000033)
	ENFILE          = Errno(0x40000017)
	ENOBUFS         = Errno(0x40000037)
	ENODATA         = Errno(0x4000006e)
	ENODEV          = Errno(0x40000013)
	ENOENT          = Errno(0x40000002)
	ENOEXEC         = Errno(0x40000008)
	ENOLCK          = Errno(0x4000004d)
	ENOLINK         = Errno(0x4000006f)
	ENOMEM          = Errno(0x4000000c)
	ENOMSG          = Errno(0x40000070)
	ENOPROTOOPT     = Errno(0x4000002a)
	ENOSPC          = Errno(0x4000001c)
	ENOSR           = Errno(0x40000071)
	ENOSTR          = Errno(0x40000072)
	ENOSYS          = Errno(0x4000004e)
	ENOTBLK         = Errno(0x4000000f)
	ENOTCONN        = Errno(0x40000039)
	ENOTDIR         = Errno(0x40000014)
	ENOTEMPTY       = Errno(0x40000042)
	ENOTRECOVERABLE = Errno(0x40000079)
	ENOTSOCK        = Errno(0x40000026)
	ENOTSUP         = Errno(0x40000076)
	ENOTTY          = Errno(0x40000019)
	ENXIO           = Errno(0x40000006)
	EOPNOTSUPP      = Errno(0x4000002d)
	EOVERFLOW       = Errno(0x40000073)
	EOWNERDEAD      = Errno(0x40000078)
	EPERM           = Errno(0x40000001)
	EPFNOSUPPORT    = Errno(0x4000002e)
	EPIPE           = Errno(0x40000020)
	EPROCLIM        = Errno(0x40000043)
	EPROCUNAVAIL    = Errno(0x4000004c)
	EPROGMISMATCH   = Errno(0x4000004b)
	EPROGUNAVAIL    = Errno(0x4000004a)
	EPROTO          = Errno(0x40000074)
	EPROTONOSUPPORT = Errno(0x4000002b)
	EPROTOTYPE      = Errno(0x40000029)
	ERANGE          = Errno(0x40000022)
	EREMOTE         = Errno(0x40000047)
	EROFS           = Errno(0x4000001e)
	ERPCMISMATCH    = Errno(0x40000049)
	ESHUTDOWN       = Errno(0x4000003a)
	ESOCKTNOSUPPORT = Errno(0x4000002c)
	ESPIPE          = Errno(0x4000001d)
	ESRCH           = Errno(0x40000003)
	ESTALE          = Errno(0x40000046)
	ETIME           = Errno(0x40000075)
	ETIMEDOUT       = Errno(0x4000003c)
	ETOOMANYREFS    = Errno(0x4000003b)
	ETXTBSY         = Errno(0x4000001a)
	EUSERS          = Errno(0x40000044)
	EWOULDBLOCK     = Errno(0x40000023)
	EXDEV           = Errno(0x40000012)
)

// Signals
const (
	SIGABRT   = Signal(0x6)
	SIGALRM   = Signal(0xe)
	SIGBUS    = Signal(0xa)
	SIGCHLD   = Signal(0x14)
	SIGCLD    = Signal(0x14)
	SIGCONT   = Signal(0x13)
	SIGEMT    = Signal(0x7)
	SIGFPE    = Signal(0x8)
	SIGHUP    = Signal(0x1)
	SIGILL    = Signal(0x4)
	SIGINFO   = Signal(0x1d)
	SIGINT    = Signal(0x2)
	SIGIO     = Signal(0x17)
	SIGIOT    = Signal(0x6)
	SIGKILL   = Signal(0x9)
	SIGLOST   = Signal(0x20)
	SIGPIPE   = Signal(0xd)
	SIGPOLL   = Signal(0x17)
	SIGPROF   = Signal(0x1b)
	SIGQUIT   = Signal(0x3)
	SIGSEGV   = Signal(0xb)
	SIGSTOP   = Signal(0x11)
	SIGSYS    = Signal(0xc)
	SIGTERM   = Signal(0xf)
	SIGTRAP   = Signal(0x5)
	SIGTSTP   = Signal(0x12)
	SIGTTIN   = Signal(0x15)
	SIGTTOU   = Signal(0x16)
	SIGURG    = Signal(0x10)
	SIGUSR1   = Signal(0x1e)
	SIGUSR2   = Signal(0x1f)
	SIGVTALRM = Signal(0x1a)
	SIGWINCH  = Signal(0x1c)
	SIGXCPU   = Signal(0x18)
	SIGXFSZ   = Signal(0x19)
)

// Error table (index: errno & 0xffff for Mach error codes)
var errors = [...]string{
	1:   "operation not permitted",
	2:   "no such file or directory",
	3:   "no such process",
	4:   "interrupted system call",
	5:   "input/output error",
	6:   "no such device or address",
	7:   "argument list too long",
	8:   "exec format error",
	9:   "bad file descriptor",
	10:  "no child processes",
	11:  "resource deadlock avoided",
	12:  "cannot allocate memory",
	13:  "permission denied",
	14:  "bad address",
	15:  "block device required",
	16:  "device or resource busy",
	17:  "file exists",
	18:  "invalid cross-device link",
	19:  "no such device",
	20:  "not a directory",
	21:  "is a directory",
	22:  "invalid argument",
	23:  "too many open files in system",
	24:  "too many open files",
	25:  "inappropriate ioctl for device",
	26:  "text file busy",
	27:  "file too large",
	28:  "no space left on device",
	29:  "illegal seek",
	30:  "read-only file system",
	31:  "too many links",
	32:  "broken pipe",
	33:  "numerical argument out of domain",
	34:  "numerical result out of range",
	35:  "resource temporarily unavailable",
	36:  "operation now in progress",
	37:  "operation already in progress",
	38:  "socket operation on non-socket",
	39:  "destination address required",
	40:  "message too long",
	41:  "protocol wrong type for socket",
	42:  "protocol not available",
	43:  "protocol not supported",
	44:  "socket type not supported",
	45:  "operation not supported",
	46:  "protocol family not supported",
	47:  "address family not supported by protocol",
	48:  "address already in use",
	49:  "cannot assign requested address",
	50:  "network is down",
	51:  "network is unreachable",
	52:  "network dropped connection on reset",
	53:  "software caused connection abort",
	54:  "connection reset by peer",
	55:  "no buffer space available",
	56:  "transport endpoint is already connected",
	57:  "transport endpoint is not connected",
	58:  "cannot send after transport endpoint shutdown",
	59:  "too many references: cannot splice",
	60:  "connection timed out",
	61:  "connection refused",
	62:  "too many levels of symbolic links",
	63:  "file name too long",
	64:  "host is down",
	65:  "no route to host",
	66:  "directory not empty",
	67:  "too many processes",
	68:  "too many users",
	69:  "disk quota exceeded",
	70:  "stale file handle",
	71:  "object is remote",
	72:  "RPC struct is bad",
	73:  "RPC version wrong",
	74:  "RPC program not available",
	75:  "RPC program version wrong",
	76:  "RPC bad procedure for program",
	77:  "no locks available",
	78:  "function not implemented",
	79:  "inappropriate file type or format",
	80:  "authentication error",
	81:  "need authenticator",
	83:  "cannot exec a shared library directly",
	100: "inappropriate operation for background process",
	101: "translator died",
	103: "you really blew it this time",
	104: "computer bought the farm",
	105: "gratuitous error",
	106: "invalid or incomplete multibyte or wide character",
	107: "bad message",
	108: "identifier removed",
	109: "multihop attempted",
	110: "no data available",
	111: "link has been severed",
	112: "no message of desired type",
	113: "out of streams resources",
	114: "device not a stream",
	115: "value too large for defined data type",
	116: "protocol error",
	117: "timer expired",
	118: "not supported",
	119: "operation canceled",
	120: "owner died",
	121: "state not recoverable",
}

// Signal table
var signals = [...]string{
	1:  "hangup",
	2:  "interrupt",
	3:  "quit",
	4:  "illegal instruction",
	5:  "trace/breakpoint trap",
	6:  "aborted",
	7:  "EMT trap",
	8:  "floating point exception",
	9:  "killed",
	10: "bus error",
	11: "segmentation fault",
	12: "bad system call",
	13: "broken pipe",
	14: "alarm clock",
	15: "terminated",
	16: "urgent I/O condition",
	17: "stopped (signal)",
	18: "stopped",
	19: "continued",
	20: "child exited",
	21: "stopped (tty input)",
	22: "stopped (tty output)",
	23: "I/O possible",
	24: "CPU time limit exceeded",
	25: "file size limit exceeded",
	26: "virtual timer expired",
	27: "profiling timer expired",
	28: "window changed",
	29: "information request",
	30: "user defined signal 1",
	31: "user defined signal 2",
	32: "resource lost",
}
