// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_redox.go (run against relibc headers via redoxer cc)

package syscall

const (
	sizeofPtr	= 0x8
	sizeofShort	= 0x2
	sizeofInt	= 0x4
	sizeofLong	= 0x8
	sizeofLongLong	= 0x8
	PathMax		= 0x1000
)

type (
	_C_short	int16
	_C_int		int32
	_C_long		int64
	_C_long_long	int64
)

type Timespec struct {
	Sec	int64
	Nsec	int64
}

type Timeval struct {
	Sec		int64
	Usec		int32
	Pad_cgo_0	[4]byte
}

type Rusage struct {
	Utime		Timeval
	Stime		Timeval
	Maxrss		int64
	Ixrss		int64
	Idrss		int64
	Isrss		int64
	Minflt		int64
	Majflt		int64
	Nswap		int64
	Inblock		int64
	Oublock		int64
	Msgsnd		int64
	Msgrcv		int64
	Nsignals	int64
	Nvcsw		int64
	Nivcsw		int64
}

type Rlimit struct {
	Cur	uint64
	Max	uint64
}

type _Pid_t int32

type _Gid_t int32

type Stat_t struct {
	Dev	uint64
	Ino	uint64
	Nlink	uint64
	Mode	int32
	Uid	int32
	Gid	int32
	Rdev	uint64
	Size	int64
	Blksize	int64
	Blocks	int64
	Atim	Timespec
	Mtim	Timespec
	Ctim	Timespec
	X_pad	[24]int8
}

type Flock_t struct {
	Type		int16
	Whence		int16
	Start		int64
	Len		int64
	Pid		int32
	Pad_cgo_0	[4]byte
}

type Dirent struct {
	Ino		uint64
	Off		int64
	Reclen		uint16
	Type		uint8
	Name		[256]int8
	Pad_cgo_0	[5]byte
}

type RawSockaddrInet4 struct {
	Family	uint16
	Port	uint16
	Addr	[4]byte /* in_addr */
	Zero	[8]int8
}

type RawSockaddrInet6 struct {
	Family		uint16
	Port		uint16
	Flowinfo	uint32
	Addr		[16]byte /* in6_addr */
	Scope_id	uint32
}

type RawSockaddrUnix struct {
	Family	uint16
	Path	[108]int8
}

type RawSockaddr struct {
	Family	uint16
	Data	[14]int8
}

type RawSockaddrAny struct {
	Addr	RawSockaddr
	Pad	[96]int8
}

type _Socklen uint32

type Linger struct {
	Onoff	int32
	Linger	int32
}

type Iovec struct {
	Base	*byte
	Len	uint64
}

type IPMreq struct {
	Multiaddr	[4]byte /* in_addr */
	Interface	[4]byte /* in_addr */
}

type IPv6Mreq struct {
	Multiaddr	[16]byte /* in6_addr */
	Interface	uint32
}

type Msghdr struct {
	Name		*byte
	Namelen		uint32
	Iov		*Iovec
	Iovlen		uint64
	Control		*byte
	Controllen	uint64
	Flags		int32
	Pad_cgo_0	[4]byte
}

type Cmsghdr struct {
	Len	uint64
	Level	int32
	Type	int32
}

const (
	SizeofSockaddrInet4	= 0x10
	SizeofSockaddrInet6	= 0x1c
	SizeofSockaddrAny	= 0x70
	SizeofSockaddrUnix	= 0x6e
	SizeofLinger		= 0x8
	SizeofIPMreq		= 0x8
	SizeofIPv6Mreq		= 0x14
	SizeofMsghdr		= 0x38
	SizeofCmsghdr		= 0x10
)

type FdSet struct {
	Bits [16]uint64
}

const (
	_AT_FDCWD = -0x64
)

type Termios struct {
	Iflag	uint32
	Oflag	uint32
	Cflag	uint32
	Lflag	uint32
	Cc	[32]uint8
}
