// Code generated by poc/mkztypes_hurd.c run on real GNU/Hurd amd64; DO NOT EDIT.

package syscall

import "unsafe"

const (
	sizeofPtr      = 0x8
	sizeofShort    = 0x2
	sizeofInt      = 0x4
	sizeofLong     = 0x8
	sizeofLongLong = 0x8
	PathMax        = 0x1000 // Hurd has no PATH_MAX
)

type (
	_C_short     int16
	_C_int       int32
	_C_long      int64
	_C_long_long int64
)

type Timespec struct {
	Sec  int64
	Nsec int64
}

type Timeval struct {
	Sec  int64
	Usec int64
}

type Rusage struct {
	Utime    Timeval
	Stime    Timeval
	Maxrss   int64
	Ixrss    int64
	Idrss    int64
	Isrss    int64
	Minflt   int64
	Majflt   int64
	Nswap    int64
	Inblock  int64
	Oublock  int64
	Msgsnd   int64
	Msgrcv   int64
	Nsignals int64
	Nvcsw    int64
	Nivcsw   int64
}

type Rlimit struct {
	Cur uint64
	Max uint64
}

type _Pid_t int32

type _Gid_t uint32

type Stat_t struct {
	Pad_cgo_0 [8]byte
	Dev       uint64
	Ino       uint64
	Pad_cgo_1 [8]byte
	Rdev      uint64
	Mode      uint32
	Pad_cgo_2 [4]byte
	Nlink     uint64
	Uid       uint32
	Gid       uint32
	Size      int64
	Atim      Timespec
	Mtim      Timespec
	Ctim      Timespec
	Blksize   int64
	Blocks    int64
	Pad_cgo_3 [56]byte
}

type Flock_t struct {
	Type      int16
	Whence    int16
	Pad_cgo_0 [4]byte
	Start     int64
	Len       int64
	Pid       int32
	Pad_cgo_1 [4]byte
}

type Dirent struct {
	Ino    uint64
	Reclen uint16
	Type   uint8
	Namlen uint8
	Name   [256]int8
}

type Termios struct {
	Iflag  uint32
	Oflag  uint32
	Cflag  uint32
	Lflag  uint32
	Cc     [20]uint8
	Ispeed uint32
	Ospeed uint32
}

type FdSet struct {
	Bits [4]int64
}

type _Socklen uint32

type RawSockaddrInet4 struct {
	Len    uint8
	Family uint8
	Port   uint16
	Addr   [4]byte
	Zero   [8]int8
}

type RawSockaddrInet6 struct {
	Len      uint8
	Family   uint8
	Port     uint16
	Flowinfo uint32
	Addr     [16]byte
	Scope_id uint32
}

type RawSockaddrUnix struct {
	Len    uint8
	Family uint8
	Path   [108]int8
}

type RawSockaddr struct {
	Len    uint8
	Family uint8
	Data   [14]int8
}

type RawSockaddrAny struct {
	Addr RawSockaddr
	Pad  [94]int8
}

type Linger struct {
	Onoff  int32
	Linger int32
}

type Iovec struct {
	Base *byte
	Len  uint64
}

type IPMreq struct {
	Multiaddr [4]byte
	Interface [4]byte
}

type IPv6Mreq struct {
	Multiaddr [16]byte
	Interface uint32
}

type Msghdr struct {
	Name       *byte
	Namelen    uint32
	Pad_cgo_0  [4]byte
	Iov        *Iovec
	Iovlen     int32
	Pad_cgo_1  [4]byte
	Control    *byte
	Controllen uint32
	Flags      int32
}

type Cmsghdr struct {
	Len   uint32
	Level int32
	Type  int32
}

type Inet6Pktinfo struct {
	Addr    [16]byte
	Ifindex uint32
}

type ICMPv6Filter struct {
	Filt [8]uint32
}

const (
	SizeofSockaddrInet4 = 0x10
	SizeofSockaddrInet6 = 0x1c
	SizeofSockaddrUnix  = 0x6e
	SizeofLinger        = 0x8
	SizeofIPMreq        = 0x8
	SizeofIPv6Mreq      = 0x14
	SizeofMsghdr        = 0x30
	SizeofCmsghdr       = 0xc
	SizeofInet6Pktinfo  = 0x14
	SizeofICMPv6Filter  = 0x20
	SizeofSockaddrAny   = 0x6e
)

const _AT_FDCWD = -100

// Compile-time layout assertions: an index into a 1-element array is only
// valid when the Go struct size equals the C size measured on Hurd.
var _ = [1]struct{}{}[unsafe.Sizeof(Timespec{})-0x10]
var _ = [1]struct{}{}[unsafe.Sizeof(Timeval{})-0x10]
var _ = [1]struct{}{}[unsafe.Sizeof(Rusage{})-0x90]
var _ = [1]struct{}{}[unsafe.Sizeof(Rlimit{})-0x10]
var _ = [1]struct{}{}[unsafe.Sizeof(Stat_t{})-0xc0]
var _ = [1]struct{}{}[unsafe.Sizeof(Flock_t{})-0x20]
var _ = [1]struct{}{}[unsafe.Sizeof(Termios{})-0x2c]
var _ = [1]struct{}{}[unsafe.Sizeof(FdSet{})-0x20]
var _ = [1]struct{}{}[unsafe.Sizeof(RawSockaddrInet4{})-0x10]
var _ = [1]struct{}{}[unsafe.Sizeof(RawSockaddrInet6{})-0x1c]
var _ = [1]struct{}{}[unsafe.Sizeof(RawSockaddrUnix{})-0x6e]
var _ = [1]struct{}{}[unsafe.Sizeof(RawSockaddr{})-0x10]
var _ = [1]struct{}{}[unsafe.Sizeof(RawSockaddrAny{})-0x6e]
var _ = [1]struct{}{}[unsafe.Sizeof(Linger{})-0x8]
var _ = [1]struct{}{}[unsafe.Sizeof(Iovec{})-0x10]
var _ = [1]struct{}{}[unsafe.Sizeof(IPMreq{})-0x8]
var _ = [1]struct{}{}[unsafe.Sizeof(IPv6Mreq{})-0x14]
var _ = [1]struct{}{}[unsafe.Sizeof(Msghdr{})-0x30]
var _ = [1]struct{}{}[unsafe.Sizeof(Cmsghdr{})-0xc]
var _ = [1]struct{}{}[unsafe.Sizeof(Inet6Pktinfo{})-0x14]
var _ = [1]struct{}{}[unsafe.Sizeof(ICMPv6Filter{})-0x20]
